Juego.MVC/Models/ErrorViewModel.cs
using System;

namespace Juego.MVC.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Juego.MVC/ViewModels/VMJuego.cs
using Jueg.Core;
using System.Collections.Generic;

namespace Juego.MVC.ViewModels
{
    public class VMJuego
    {
        public IEnumerable<Genero> Generos { get; set; }
        public Juego Juego { get; set; }
        public int? IdGeneroSeleccionado { get; set; }
        public VMJuego() => Juego = new Juego();
        public VMJuego(IEnumerable<Genero> generos) : this()
            => Generos = generos;

        public VMJuego(Juego juego)
        {
            Juego = juego;
        }
    }
}

Juego.MVC/Controllers/GeneroController.cs
using Microsoft.AspNetCore.Mvc;
using Juego.Core;

namespace Juego.Controllers
{
    public class GeneroController : Controller
    {

        [HttpGet]
        public IActionResult Index()
        => View(Repositorio.Generos);

        [HttpGet]
        public IActionResult Detalle(int id)
        {
            var Genero = Repositorio.GetGenero(id);
            if (Genero is null)
            {
                return NotFound();
            }
            return View(Genero);
        }
        [HttpGet]

        public IActionResult FormAlta() => View();

        [HttpPost]

        public IActionResult FormAlta(Genero genero)
        {
            Repositorio.AgregarGenero(genero);
            return View("index", Repositorio.Generos);
        }

    }
}

Juego.MVC/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Juego.MVC.Models;

namespace Juego.MVC.Controllers
{
    public class HomeController : Controller
    {

        public IActionResult index()
        {
            return View();
        }
    }}

Juego.MVC/Controllers/JuegoController.cs
using Microsoft.AspNetCore.Mvc;
using Juego.Core;
using Juego.MVC.ViewModels;

namespace Juego.Controllers
{
    public class JuegoController : Controller
    {

        [HttpGet]
        public IActionResult Index()
        => View(Repositorio.Juegos);

        [HttpGet]
        public IActionResult Detalle(int id)
        {
            var Juego = Repositorio.GetJuego(id);
            if (Juego is null)
            {
                return NotFound();
            }
            return View(Juego);
        }
        [HttpGet]

        public IActionResult FormAlta(int? idGenero)
        {
            var vmJuego= new VMJuego(Repositorio.Generos)
            {
            IdGeneroSeleccionado = idGenero
            };
            return View(vmJuego);
        }

        [HttpPost]
        public IActionResult FormAlta(VMJuego vMJuego)
        {
            if (Validar(vMJuego))
            {
                var genero = Repositorio.GetGenero(vMJuego.IdGeneroSeleccionado.Value);
                genero.AgregarJuego(vMJuego.Juego);
                Repositorio.AgregarJuego(vMJuego.Juego);
            }
            return View("Index", Repositorio.Juegos);
        }
        [HttpPost]
        public IActionResult Modificar(VMJuego vmJuego)
        {
            if (Validar(vmJuego))
            {
                var juego = Repositorio.GetJuego(vmJuego.Juego.Id);
                if (juego is null)
                {
                    return NotFound();
                }
            }
            return View("Index", Repositorio.Juegos);
        }
        private bool Validar(VMJuego vMJuego)
            => (vMJuego.IdGeneroSeleccionado.HasValue);
    }
}

Juego.MVC/Views/Genero/Detalle.cshtml
@model Juego.Core.Genero
@{
    Layout = null;
}

<!DOCTYPE html>
<html >
<head>
<title>Juego Detalle @Model.Nombre</title>
</head>
<body>

</body>
</html>

Juego.MVC/Views/Genero/FormAlta.cshtml
@model Juego.Core.Genero
@{
    Layout = null;
}
<!DOCTYPE html>
<head>
    <title>Juego Genero</title>
</head>
<body>
    <form asp-action="FormAlta" method="post">
        <div asp-validation-summary="All"></div>
        <div>
            <label asp-for="Nombre">GENEROS:</label>
            <input asp-for="Nombre" />
        </div>
        <button type="submit">Alta Genero</button>
    </form>
</body>
</html>

Juego.MVC/Views/Genero/Index.cshtml
@model  IEnumerable<Juego.Core.Genero>
@{
    Layout = null;
}
<html>
    <head>
        <title>Juego Genero</title>
    </head>
    <body>
<h1>Generos</h1>
<table>
    <thead>
    <td>Nombre</td>
    </thead>
    <tbody>
    @foreach (Juego.Core.Genero genero in Model)
    {
        <tr>
        <td>
        <a asp-controller="Genero" asp-action="Detalle" asp-route-id="@genero.Id">@genero.Nombre</a> 
        </td>
        </tr>
    }
    </tbody>
</table>
    </body>
</html>

Juego.MVC/Views/Home/Index.cshtml
@{
    Layout = null;
}
<!DOCTYPE html>
<html>
<head>
    <title>Juegos</title>
</head>
<body> 
    <a asp-controller="Genero" asp-action="Index">Ver Generos</a><br />
    <a asp-controller="Genero"asp-action="FormAlta">Alta Genero</a>
<br/>
<br/>

    <a asp-controller="Juego" asp-action="Index">Ver Juegos</a><br />
    <a asp-controller="Juego"asp-action="FormAlta">Alta Juego</a>

</body>
</html>

Juego.MVC/Views/Juego/Detalle.cshtml
@model Juego.Core.Juego
@{
    Layout = null;
}
<!DOCTYPE html>
<html>
<head>
    <title>Detalle @Model.Nombre</title>
</head>
<body>
    <div>
        <h3>@Model.Nombre</h3>
        Fecha de estreno: @Model.FechaEstreno<br>
        Descripcion: @Model.Descripcion<br>
        Peso: @Model.Peso<br />
        Genero: @Model.Genero<br />
    </div>
    <hr />
</body>
</html>

Juego.MVC/Views/Juego/FormAlta.cshtml
@model Juego.MVC.ViewModels.VMJuego;
@{
    Layout = null;
}
<!DOCTYPE html>
<html>
<head>
    <title>Juego</title>
</head>
<body>
    <form asp-action="FormAlta" method="post">
        <div asp-validation-summary="All"></div>
        <div>
            <label asp-for="@Model.Juego.Nombre">Nombre:</label>
            <input asp-for="@Model.Juego.Nombre" />
        </div>
        <div>
            <label asp-for="@Model.FechaEstreno">Fecha de estreno:</label>
            <input asp-for="@Model.FechaEstreno">
        </div>
        <div>
            <label asp-for="@Model.Juego.Descripcion">Descripcion:</label>
            <input asp-for="@Model.Juego.Descripcion">
        </div>
        <div>
            <select asp-for="IdGeneroSeleccionado">
                <option value="">Elegi una opción</option>
                @foreach (Juegos.Core.Genero genero in Model.Generos)
                {
                    <option value="@genero.Id">@genero.Nombre</option>
                }
            </select>
        </div>
        <button type="submit">Alta Producto</button>
    </form>
</body>
</html>

Juego.MVC/Views/Juego/Index.cshtml
@model IEnumerable<Juego.Core.Juego>
@{
    Layout = null;
}
<!DOCTYPE html>
<html>
<head>
    <title>Juego</title>
</head>
<body>
    <a asp-action="FormAlta">Alta Juego</a><br />
    <h5>Juego</h5>
    <table>
        <thead>
            <tr><td>Nombre</td></tr>
        </thead>
        <tbody>
            @foreach (Juego.Core.Juego juego in Model)
            {
                <tr>
                    <td>
                        <a asp-controller="Juego" asp-action="Detalle" asp-route-id="@juego.Id">@juego.Nombre</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
    <hr />
    <a asp-controller="Genero" asp-action="Index">Generos</a>
</body>
</html>

Juego.MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Juego.MVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Juego.MVC</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Juego.MVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>